# Computation, Problem Set #1b
## Intro to NumPy

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import math
import sympy as sy

### Problem 1

In [80]:
A = np.array([[3,-1,4],[1,5,-9]])
B = np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
AB = A@B
print(AB)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


### Problem 2

In [81]:
A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
-A@A@A + 9*A@A - 15*A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Problem 3

In [82]:
A = np.triu(np.ones((7,7)))
B = np.tril(np.full_like(A,-1))\
+(np.full_like(A,5)-np.tril(np.full_like(A,5)))
A = A.astype(np.int64)
B = B.astype(np.int64)
print(A)
print(B)

[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]
[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]


### Problem 4

In [83]:
def change_input(x):
    mask = x < 0
    x[mask] = 0
    return x
print(B)
print(change_input(B))

[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]
[[0 5 5 5 5 5 5]
 [0 0 5 5 5 5 5]
 [0 0 0 5 5 5 5]
 [0 0 0 0 5 5 5]
 [0 0 0 0 0 5 5]
 [0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0]]


### Problem 5

In [85]:
A = np.arange(6).reshape((3,2)).T
B = np.tril(np.ones((3,3))*3)
C = np.eye(3)*(-2)
Row1 = np.hstack((np.zeros((3,3)),A.T,np.eye(3)))
Row2 = np.hstack((A,np.zeros((2,2)),np.zeros((2,3))))
Row3 = np.hstack((B,np.zeros((3,2)),C))
np.vstack((Row1,Row2,Row3))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

### Problem 6

In [86]:
def row_stochastic(x):
    rowsum = x.sum(axis=1)
    rowsum = rowsum.reshape((-1,1))
    Stochastic_x = x / rowsum
    return Stochastic_x

print(A)
row_stochastic(A)

[[0 2 4]
 [1 3 5]]


array([[0.        , 0.33333333, 0.66666667],
       [0.11111111, 0.33333333, 0.55555556]])

### Problem 7

In [87]:
def max_four_product(x):
    max_col = np.max(x[:,:-3]*x[:,1:-2]*x[:,2:-1]*x[:,3:])
    max_row = np.max(x[:-3,:]*x[1:-2,:]*x[2:-1,:]*x[3:,:])
    max_right_diag = np.max(x[:-3,3:]*x[1:-2,2:-1]*x[2:-1,1:-2]*x[3:,:-3])
    max_left_diag = np.max(x[3:,:-3]*x[2:-1,1:-2]*x[1:-2,2:-1]*x[:-3,3:])
    
    print(max_col,max_row,max_right_diag,max_left_diag)
    maximum = max(max_col,max_row,max_right_diag,max_left_diag)
    return maximum

grid = np.load("grid.npy")
max_four_product(grid)

48477312 51267216 70600674 70600674


70600674

### End