# OSE-Summer School 2019
## Wk3: ECON DSGE PS1, Kerk Phillips

In [44]:
import numpy as np
from matplotlib import pyplot as plt
from scipy.optimize import fsolve
import sys

### Exercise 1

In the steady state, the euler equation becomes:

$$ \frac{1}{\bar{K}^{\alpha}-\bar{K}} = \frac{\alpha\beta\bar{K}^{\alpha-1}}{\bar{K}^{\alpha}-\bar{K}} $$

Thus, $\bar{K} = (\alpha\beta)^{\frac{1}{1-\alpha}} = A^{\frac{1}{1-\alpha}} $ and $ A = \alpha\beta $.

### Exercise 2

$$ c_{t}^{-1} = \beta \mathbb{E}_{t}\big[c_{t+1}^{-1}\big((r_{t+1}-\delta)(1-\tau)+1 \big)\big] $$

$$ a(1-l_{t})^{-1} = c_{t}^{-1}w_{t}(1-\tau) $$

$$ r_{t} = \alpha e^{z_{t}} k_{t}^{\alpha-1} l_{t}^{1-\alpha} $$

$$ w_{t} = (1-\alpha) e^{z_{t}} k_{t}^{\alpha} l_{t}^{-\alpha} $$

$$ \tau(w_{t}l_{t} + (r_{t}-\delta)k_{t}) = T_{t} $$

$$ c_{t} = (1-\tau) \big(w_{t}l_{t} + (r_{t}-\delta)k_{t} \big) + k_{t} + T_{t} - k_{t+1} $$

### Exercise 3

$$ c_{t}^{-\gamma} = \beta \mathbb{E}_{t}\big[c_{t+1}^{-\gamma}\big((r_{t+1}-\delta)(1-\tau)+1 \big)\big] $$

$$ a(1-l_{t})^{-1} = c_{t}^{-\gamma}w_{t}(1-\tau) $$

$$ r_{t} = \alpha e^{z_{t}} k_{t}^{\alpha-1} l_{t}^{1-\alpha} $$

$$ w_{t} = (1-\alpha) e^{z_{t}} k_{t}^{\alpha} l_{t}^{-\alpha} $$

$$ \tau(w_{t}l_{t} + (r_{t}-\delta)k_{t}) = T_{t} $$

$$ c_{t} = (1-\tau) \big(w_{t}l_{t} + (r_{t}-\delta)k_{t} \big) + k_{t} + T_{t} - k_{t+1} $$

### Exercise 4

$$ c_{t}^{-\gamma} = \beta \mathbb{E}_{t}\big[c_{t+1}^{-\gamma}\big((r_{t+1}-\delta)(1-\tau)+1 \big)\big] $$

$$ a(1-l_{t})^{-\xi} = c_{t}^{-\gamma}w_{t}(1-\tau) $$

$$ r_{t} = \alpha e^{z_{t}} k_{t}^{\eta-1} \big[\alpha k_{t}^{\eta}+(1-\alpha)l_{t}^{\eta} \big]^{\frac{1-\eta}{\eta}} $$

$$ w_{t} = (1-\alpha) e^{z_{t}} l_{t}^{\eta-1} \big[\alpha k_{t}^{\eta}+(1-\alpha)l_{t}^{\eta} \big]^{\frac{1-\eta}{\eta}} $$

$$ \tau(w_{t}l_{t} + (r_{t}-\delta)k_{t}) = T_{t} $$

$$ c_{t} = (1-\tau) \big(w_{t}l_{t} + (r_{t}-\delta)k_{t} \big) + k_{t} + T_{t} - k_{t+1} $$

### Exercise 5

$$ c_{t}^{-\gamma} = \beta \mathbb{E}_{t}\big[c_{t+1}^{-\gamma}\big((r_{t+1}-\delta)(1-\tau)+1 \big)\big] $$

$$ r_{t} = \alpha e^{z_{t}} k_{t}^{\alpha-1} $$

$$ w_{t} = (1-\alpha) e^{z_{t}} k_{t}^{\alpha} $$

$$ \tau(w_{t} + (r_{t}-\delta)k_{t}) = T_{t} $$

$$ c_{t} = (1-\tau) \big(w_{t} + (r_{t}-\delta)k_{t} \big) + k_{t} + T_{t} - k_{t+1} $$

In the steady state,

$$ 1 = \beta [ (\bar{r}-\delta)(1-\tau)+1 ] $$

$$ \bar{r} = \alpha \bar{k}^{\alpha-1} $$

$$ \bar{w} = (1-\alpha) \bar{k}^{\alpha} $$

$$ \tau(\bar{w} + (\bar{r}-\delta)\bar{k}) = \bar{T} $$

$$ \bar{c} = (1-\tau) \big(\bar{w} + (\bar{r}-\delta)\bar{k} \big) + \bar{T} $$

In [1]:
import numpy as np
import sympy as sy
from matplotlib import pyplot as plt
from mpl_toolkits import mplot3d
from scipy.optimize import fsolve
import sys

In [2]:
# parameters
γ = 2.50
α = 0.40
β = 0.98
δ = 0.10
τ = 0.05

In [3]:
# anlaytical solution
rss = (1-β)/(β*(1-τ))+δ
kss = ((1/α)*rss)**(1/(α-1))
wss = (1-α)*kss**α
css = wss+(rss-δ)*kss
Tss = τ*(wss+(rss-δ)*kss)
Oss = kss**α
iss = δ*kss

In [4]:
# numerical solution
def steady_state_ex5(var):
    
    r,k,w,c,T = var
    
    eq1 = 1 - β*((r-δ)*(1-τ) + 1)
    eq2 = r - α*k**(α-1)
    eq3 = w - (1-α)*k**α
    eq4 = c - w - (r-δ)*k
    eq5 = T - τ*(w + (r-δ)*k)

    return (eq1, eq2, eq3, eq4, eq5)

rssN, kssN, wssN, cssN, TssN = fsolve(steady_state_ex5, (0.1, 1, 1, 1, 0.1))
OssN = kssN**α
issN = δ*kssN

In [5]:
print("[Steady state values (algebraic solution)]")
print("")
print('interest rate(r):',round(rss,4))
print('capital stock(k):',round(kss,4))
print('wage(w)         :',round(wss,4))
print('consumption(c)  :',round(css,4))
print('tax revenue(T)  :',round(Tss,4))
print('output(O)       :',round(Oss,4))
print('investment(i)   :',round(iss,4))
print("")
      
print("[Steady state values (numerical solution)]")
print("")
print('interest rate(r):',round(rssN,4))
print('capital stock(k):',round(kssN,4))
print('wage(w)         :',round(wssN,4))
print('consumption(c)  :',round(cssN,4))
print('tax revenue(T)  :',round(TssN,4))
print('output(O)       :',round(OssN,4))
print('investment(i)   :',round(issN,4))

[Steady state values (algebraic solution)]

interest rate(r): 0.1215
capital stock(k): 7.2875
wage(w)         : 1.328
consumption(c)  : 1.4845
tax revenue(T)  : 0.0742
output(O)       : 2.2133
investment(i)   : 0.7287

[Steady state values (numerical solution)]

interest rate(r): 0.1215
capital stock(k): 7.2875
wage(w)         : 1.328
consumption(c)  : 1.4845
tax revenue(T)  : 0.0742
output(O)       : 2.2133
investment(i)   : 0.7287


### Exercise 6

$$ c_{t}^{-\gamma} = \beta \mathbb{E}_{t}\big[c_{t+1}^{-\gamma}\big((r_{t+1}-\delta)(1-\tau)+1 \big)\big] $$

$$ a(1-l_{t})^{-\xi} = c_{t}^{-\gamma}w_{t}(1-\tau) $$

$$ r_{t} = \alpha k_{t}^{\alpha-1} (l_{t}e^{z_{t}})^{1-\alpha} $$

$$ w_{t} = (1-\alpha) k_{t}^{\alpha} l_{t}^{-\alpha} e^{z_{t}(1-\alpha)} $$

$$ \tau(w_{t}l_{t} + (r_{t}-\delta)k_{t}) = T_{t} $$

$$ c_{t} = (1-\tau) \big(w_{t}l_{t} + (r_{t}-\delta)k_{t} \big) + k_{t} + T_{t} - k_{t+1} $$

In the steady state,

$$ 1 = \beta [ (\bar{r}-\delta)(1-\tau)+1 ] $$

$$ a(1-\bar{l})^{-\xi} = (\bar{c})^{-\gamma} \bar{w}(1-\tau) $$

$$ \bar{r} = \alpha (\bar{k})^{\alpha-1} (\bar{l})^{1-\alpha} $$

$$ \bar{w} = (1-\alpha) (\bar{k})^{\alpha} (\bar{l})^{-\alpha} $$

$$ \tau(\bar{w}\bar{l} + (\bar{r}-\delta)\bar{k}) = \bar{T} $$

$$ \bar{c} = (1-\tau) \big(\bar{w}\bar{l} + (\bar{r}-\delta)\bar{k} \big) + \bar{T} $$

In [6]:
# parameters
γ = 2.50
ξ = 1.50
α = 0.40
β = 0.98
δ = 0.10
τ = 0.05
a = 0.50

In [7]:
# numerical solution
def steady_state_ex6(var):
    
    r,k,l,w,c,T = var
    
    eq1 = 1 - β * ((r-δ)*(1-τ) + 1)
    eq2 = a * ((1-l)**(-ξ)) - (c**(-γ))*w*(1-τ)
    eq3 = r - α * (k**(α-1)) * (l**(1-α))
    eq4 = w - (1-α) * (k**α) * (l**(-α))
    eq5 = T - τ * (w*l + (r-δ)*k)
    eq6 = c - (1-τ) * (w*l + (r-δ)*k) - T

    return (eq1, eq2, eq3, eq4, eq5, eq6)

rss, kss, lss, wss, css, Tss = fsolve(steady_state_ex6, (0.2, 1, 0.5, 1, 1, 0.1))
Oss = kss**α * lss**(1-α)
iss = δ*kss

print("[Steady state values]")
print("")
print('interest rate(r):',round(rss,4))
print('capital stock(k):',round(kss,4))
print('labor(l)        :',round(lss,4))
print('wage(w)         :',round(wss,4))
print('consumption(c)  :',round(css,4))
print('tax revenue(T)  :',round(Tss,4))
print('output(O)       :',round(Oss,4))
print('investment(i)   :',round(iss,4))
print("")

[Steady state values]

interest rate(r): 0.1215
capital stock(k): 4.2252
labor(l)        : 0.5798
wage(w)         : 1.328
consumption(c)  : 0.8607
tax revenue(T)  : 0.043
output(O)       : 1.2832
investment(i)   : 0.4225



### Exercise 7

In [8]:
def steady_state_ex7(var,*args):
    
    r,k,l,w,c,T = var
    α,β,γ,δ,ξ,τ,a,z = args
           
    eq1 = 1 - β * ((r-δ)*(1-τ) + 1)
    eq2 = a * ((1-l)**(-ξ)) - (c**(-γ))*w*(1-τ)
    eq3 = r - α * (k**(α-1)) * ((l*np.exp(z))**(1-α))
    eq4 = w - (1-α) * (k**α) * (l**(-α)) * np.exp(z*(1-α))
    eq5 = T - τ * (w*l + (r-δ)*k)
    eq6 = c - (1-τ) * (w*l + (r-δ)*k) - T

    return (eq1, eq2, eq3, eq4, eq5, eq6)


def compute_ss(params):
    
    α,β,γ,δ,ξ,τ,a,zss = params
    init_guess = [0.2, 1, 0.5, 1, 1, 0.2]
    
    # compute the steady state given parameters
    rss, kss, lss, wss, css, Tss = fsolve(steady_state_ex7, init_guess, params)
    
    # compute output(Oss) and investment(iss)
    Oss = kss**α * (lss*np.exp(zss))**(1-α)
    iss = δ*kss
    
    return (rss, kss, lss, wss, css, Tss, Oss, iss)

In [9]:
# initial parameters
α, β, γ, δ, ξ, τ, a, zss = 0.4, 0.98, 2.5, 0.1, 1.5, 0.05, 0.5, 0
params = (α,β,γ,δ,ξ,τ,a,zss)

In [10]:
# check the initial steady state values
rss, kss, lss, wss, css, Tss, Oss, iss = compute_ss(params)

print("[Initial Steady state values]")
print("")
print('interest rate(r):',round(rss,4))
print('capital stock(k):',round(kss,4))
print('labor(l)        :',round(lss,4))
print('wage(w)         :',round(wss,4))
print('consumption(c)  :',round(css,4))
print('tax revenue(T)  :',round(Tss,4))
print('output(O)       :',round(Oss,4))
print('investment(i)   :',round(iss,4))
print("")

[Initial Steady state values]

interest rate(r): 0.1215
capital stock(k): 4.2252
labor(l)        : 0.5798
wage(w)         : 1.328
consumption(c)  : 0.8607
tax revenue(T)  : 0.043
output(O)       : 1.2832
investment(i)   : 0.4225



In [11]:
# compute derivatives using numerical differentiation
init_ss = [rss, kss, lss, wss, css, Tss, Oss, iss]
ϵ = 0.0001
Etuple = (0,) * (len(init_ss)-1) + (ϵ,)*1 + (0,) * (len(init_ss)-1)
ay_ax = np.zeros((len(params),len(init_ss)))

for ix in range(len(params)):
    
    E = Etuple[len(params)-1-ix : len(Etuple)-ix]
    params_up = tuple(np.add(params, E))
    params_down = tuple(np.subtract(params, E))
    
    r, k, l, w, c, T, O, i = compute_ss(params_up)
    ss_up = [r, k, l, w, c, T, O, i]
    
    r, k, l, w, c, T, O, i = compute_ss(params_down)
    ss_down = [r, k, l, w, c, T, O, i]
    
    for iy in range(len(init_ss)):
        ay_ax[ix,iy] = (ss_up[iy] - ss_down[iy]) / (2*ϵ)
    

print("(the derivative of Y w.r.t α)")
print("[dr/dα, dk/dα, dl/dα, dw/dα, dc/dα, dT/dα, dO/dα, di/dα] = ")
print(np.round(ay_ax[0,:],3))
print("")

print("(the derivative of Y w.r.t β)")
print("[dr/dβ, dk/dβ, dl/dβ, dw/dβ, dc/dβ, dT/dβ, dO/dβ, di/dβ] = ")
print(np.round(ay_ax[1,:],3))
print("")

print("(the derivative of Y w.r.t γ)")
print("[dr/dγ, dk/dγ, dl/dγ, dw/dγ, dc/dγ, dT/dγ, dO/dγ, di/dγ] = ")
print(np.round(ay_ax[2,:],3))
print("")

print("(the derivative of Y w.r.t δ)")
print("[dr/dδ, dk/dδ, dl/dδ, dw/dδ, dc/dδ, dT/dδ, dO/dδ, di/dδ] = ")
print(np.round(ay_ax[3,:],3))
print("")

print("(the derivative of Y w.r.t ξ)")
print("[dr/dξ, dk/dξ, dl/dξ, dw/dξ, dc/dξ, dT/dξ, dO/dξ, di/dξ] = ")
print(np.round(ay_ax[3,:],3))
print("")

print("(the derivative of Y w.r.t τ)")
print("[dr/dτ, dk/dτ, dl/dτ, dw/dτ, dc/dτ, dT/dτ, dO/dτ, di/dτ] = ")
print(np.round(ay_ax[5,:],3))
print("")

print("(the derivative of Y w.r.t a)")
print("[dr/da, dk/da, dl/da, dw/da, dc/da, dT/da, dO/da, di/da] = ")
print(np.round(ay_ax[6,:],3))
print("")

print("(the derivative of Y w.r.t z)")
print("[dr/dz, dk/dz, dl/dz, dw/dz, dc/dz, dT/dz, dO/dz, di/dz] = ")
print(np.round(ay_ax[7,:],3))
print("")

(the derivative of Y w.r.t α)
[dr/dα, dk/dα, dl/dα, dw/dα, dc/dα, dT/dα, dO/dα, di/dα] = 
[ 0.    25.985 -0.769  4.396  2.085  0.104  4.684  2.598]

(the derivative of Y w.r.t β)
[dr/dβ, dk/dβ, dl/dβ, dw/dβ, dc/dβ, dT/dβ, dO/dβ, di/dβ] = 
[-1.096 65.431  0.26   7.987  1.751  0.088  8.294  6.543]

(the derivative of Y w.r.t γ)
[dr/dγ, dk/dγ, dl/dγ, dw/dγ, dc/dγ, dT/dγ, dO/dγ, di/dγ] = 
[ 0.     0.139  0.019 -0.     0.028  0.001  0.042  0.014]

(the derivative of Y w.r.t δ)
[dr/dδ, dk/dδ, dl/dδ, dw/dδ, dc/dδ, dT/dδ, dO/dδ, di/dδ] = 
[  1.    -48.35    1.32   -7.288  -3.511  -0.176  -4.121  -0.61 ]

(the derivative of Y w.r.t ξ)
[dr/dξ, dk/dξ, dl/dξ, dw/dξ, dc/dξ, dT/dξ, dO/dξ, di/dξ] = 
[  1.    -48.35    1.32   -7.288  -3.511  -0.176  -4.121  -0.61 ]

(the derivative of Y w.r.t τ)
[dr/dτ, dk/dτ, dl/dτ, dw/dτ, dc/dτ, dT/dτ, dO/dτ, di/dτ] = 
[ 0.023 -2.323 -0.139 -0.165 -0.234  0.849 -0.467 -0.232]

(the derivative of Y w.r.t a)
[dr/da, dk/da, dl/da, dw/da, dc/da, dT/da, dO/da, di/da] = 


### End